import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useRequestLocation } from "./helper/requestLocation";
import WeatherSection from "./weatherSection";

const Home: NextPage = () => {
  const location = useRequestLocation();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <WeatherSection location={location}/>
      </main>
    </div>
  );
};

export default Home;
